### ISSUE TITLE
[Card issue] Weavile-GX cannot perform other actions after using its ability

### ISSUE THREAD

**Issue by Hill-98** [Hastwell/Omukade.Cheyenne#5] opened 2024-03-19 13:39 UTC
Weavile-GX ability is: As often as you like during your turn (before your attack), you may move a basic dark Energy from 1 of your Pokémon to another of your Pokémon.

When players are connected to Omukade.Cheyenne for gameplay, Energy moves and no further actions can be continued.

**Comment by Hill-98** [comment] 2024-03-19 20:08
This video demo

https://github.com/Hastwell/Omukade.Cheyenne/assets/25147395/6a9edfe4-7e30-4d4c-8c04-36ec0887deb8

https://github.com/Hastwell/Omukade.Cheyenne/assets/25147395/7c6192e6-95c5-4cd6-8848-317a85f24cfb

**Comment by Hastwell** [comment] 2024-03-20 07:49
The root cause has been identified (bad serialization code called when processing the first card chosen for certain types of select-multiple-cards effects), and resolved by dcd31fdc4131868c89ad1a032c5d5ad978a9f11d

Thank you for this report, and the excellent demo videos you recorded!

**Closed as completed by Hastwell** 2024-03-20 07:49 UTC
